name: primera_app_fluttrer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.5.0
  flutter_swiper_null_safety: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/splash2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
